name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: distsystem/.github/.github/workflows/release-pixi.yaml@main
    secrets: inherit
